-- AIOps Semantic Error Intelligence Platform
-- Oracle AI Database 26ai - Schema Init
-- Fixed for SQLPlus: no blank lines inside DDL statements

-- Drop existing objects safely
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX SS_ERROR_LOGS_VIDX';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SS_ERROR_LOGS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Create main table (no blank lines inside - SQLPlus requirement)
CREATE TABLE SS_ERROR_LOGS (
    LOG_ID            VARCHAR2(100)   PRIMARY KEY,
    EVENT_TIME        TIMESTAMP,
    FLOW_CODE         VARCHAR2(200),
    ACTION_NAME       VARCHAR2(200),
    ENDPOINT_NAME     VARCHAR2(200),
    ERROR_LEVEL       VARCHAR2(50),
    ERROR_CODE        VARCHAR2(100),
    SEMANTIC_TEXT     CLOB,
    RAW_JSON          CLOB,
    ATTRIBUTES        JSON,
    VECTOR            VECTOR(3072, FLOAT32)
);

-- HNSW vector index for ANN cosine similarity search
CREATE VECTOR INDEX SS_ERROR_LOGS_VIDX
ON SS_ERROR_LOGS(VECTOR)
ORGANIZATION INMEMORY GRAPH
DISTANCE COSINE
WITH TARGET ACCURACY 95;

-- Metadata indexes for filtering
CREATE INDEX SS_ERROR_LOGS_FLOW_IDX ON SS_ERROR_LOGS(FLOW_CODE);

CREATE INDEX SS_ERROR_LOGS_TIME_IDX ON SS_ERROR_LOGS(EVENT_TIME);

CREATE INDEX SS_ERROR_LOGS_LEVEL_IDX ON SS_ERROR_LOGS(ERROR_LEVEL);

-- Verify setup
SELECT 'TABLE CREATED OK' AS STATUS FROM USER_TABLES WHERE TABLE_NAME = 'SS_ERROR_LOGS';
SELECT INDEX_NAME, INDEX_TYPE FROM USER_INDEXES WHERE TABLE_NAME = 'SS_ERROR_LOGS';

EXIT;